name: mindset
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^2.3.0

  # Navigation
  go_router: ^14.1.0

  # DI
  get_it: ^7.7.0
  injectable: ^2.4.0

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_analytics: ^11.0.1
  google_sign_in: ^6.2.1

  # Local DB
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

  # Network & Utils
  connectivity_plus: ^6.0.3
  http: ^1.2.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  uuid: ^4.4.0
  intl: ^0.19.0

  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  youtube_player_flutter: ^9.0.1
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.6
  flutter_tts: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.4.2
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
        - asset: assets/fonts/NotoSansDevanagari-Bold.ttf
          weight: 700
